# Census Data Collector `censusdc` basic example

This example shows the basic usage of the census data collector using all supported queryable products:

* Tigerweb
* Summary File 3 of the Decennial Census (SF3)
* Acs 1-Year
* Acs 5-Year

Start by importing some necessary packages for this example

In [1]:
from pathlib import Path
import geopandas as gpd
import matplotlib.pyplot as plt
from matplotlib.collections import PatchCollection

and import classes from the census data collector

In [2]:
from censusdc import TigerWeb, Acs1, Acs5, Sf3

### Note: a census API key is necessary for this example. Please redefine the `apikey` variable to reflect your personal census API key

A personal API key can be obtained from https://api.census.gov/data/key_signup.html

In [3]:
apikey = Path("../api_key.dat")
with open(apikey) as api:
    apikey = api.readline().strip()

## Grab census designated place information from TigerWeb

TigerWeb provides census geographies and geocodes that can be used to spatialally query data from census products. TigerWeb data calls return geoJSON features. We'll be grabbing tigerweb infromation for a couple Sacramento, CA neighborhoods using this shapefile

<p align="center">
  <img src="https://raw.githubusercontent.com/jlarsen-usgs/census-data-collector/master/data/Sacramento_neighborhoods.png" alt="Sacto"/>
</p>

In [7]:
shp_file = Path('../data/Sacramento_neighborhoods.shp')
gdf = gpd.read_file(shp_file)
gdf.head()

   Id        name                                           geometry
0   0  La_riviera  POLYGON ((122918.078 4278978.134, 123057.108 4...
1   0  Tahoe_park  POLYGON ((111068.007 4277472.914, 111256.009 4...

The shapefile can have multiple polygons defined and will be treated as multiple features. If there is a specific association for the polygon within the shapefile we can tag it using one of the `TigerWeb` class parameters. The `TigerWeb` class parameters include:

* `gdf`: geopandas GeoDataFrame
* `field`: shapefile attribute to identify multiple polygons

In [8]:
tigweb = TigerWeb(gdf, field='name')

__Querying data using the `TigerWeb` class__

Once we instantiate the `TigerWeb` class it can be used to query data from the census TigerWeb REST servers using the `get_data()` method. The `get_data()` method has a number of optional parameters that can be passed to it, however it is recommended that the user uses the defaults unless they have a good understanding of the census data product they are requesting. `get_data()` parameters are:

* `year`: Year of data request (1990, 2000, and 2004 - 2024 are supported)
* `level`: default "finest", census designated place level ("tract" and/or "county" are recommended options)
* `outfields`: TigerWeb rest server variables. Default `()` grabs most TigerWeb variables

Let's grab tract level data for the 2000 Decenial census

In [9]:
tigweb.get_data(2000, level='tract')

Received 13 entries, 13 total, from server 8
Received 6 entries, 6 total, from server 8

We can examine this data by grabbing a copy of the features using the `get_feature()` method. This returns a list of geoJSON features.

In [10]:
# get the feature names
names = tigweb.feature_names
print(names)

la_riv = tigweb.get_feature(names[0])
la_riv

['La_riviera', 'Tahoe_park']

,geometry,GEOID,STATE,COUNTY,TRACT,AREAWATER,name
0,"POLYGON ((116650.003 4277424.314, 116443.385 4...",06067005202,06,067,005202,113923,La_riviera
1,"POLYGON ((120975.148 4278730.642, 120878.463 4...",06067005804,06,067,005804,368436,La_riviera
2,"POLYGON ((118484.777 4273176.598, 118689.226 4...",06067005203,06,067,005203,0,La_riviera
3,"POLYGON ((119197.121 4275581.295, 119292.682 4...",06067009109,06,067,009109,0,La_riviera
4,"POLYGON ((121173.805 4278832.06, 121344.525 42...",06067005803,06,067,005803,0,La_riviera
5,"POLYGON ((123808.733 4278389.86, 123808.112 42...",06067009006,06,067,009006,0,La_riviera
6,"POLYGON ((114837.276 4277486.301, 114832.988 4...",06067005201,06,067,005201,168225,La_riviera
7,"POLYGON ((117346.391 4278671.9, 117312.967 427...",06067005404,06,067,005404,164181,La_riviera
8,"POLYGON ((120990.696 4278702.974, 120181.252 4...",06067009107,06,067,009107,367880,La_riviera
9,"POLYGON ((118771.957 4276961.927, 118693.692 4...",06067009110,06,067,009110,0,La_riviera
10,"POLYGON ((123012.816 4281274.724, 122779.299 4...",06067008909,06,067,008909,352472,La_riviera
11,"POLYGON ((119406.006 4277989.833, 118521.327 4...",06067009106,06,067,009106,195740,La_riviera
12,"POLYGON ((118947.261 4276976.94, 118963.147 42...",06067009105,06,067,009105,0,La_riviera

We can also define which variable we would like to get in a data pull by using supplying tigerweb variable names to the `outfields` parameter of the `get_data()` method.

Let's rerun the data pull using variables from `TigerWebVariables` class

In [11]:
from censusdc import TigerWebVariables

outfields = (TigerWebVariables.state, TigerWebVariables.county, TigerWebVariables.tract)
tigweb.get_data(2000, level='tract', outfields=outfields)

names = tigweb.feature_names
la_riv = tigweb.get_feature(names[0])
la_riv

Received 13 entries, 13 total, from server 8
Received 6 entries, 6 total, from server 8

,geometry,STATE,COUNTY,TRACT,GEOID,name
0,"POLYGON ((116650.003 4277424.314, 116443.385 4...",06,067,005202,06067005202,La_riviera
1,"POLYGON ((120975.148 4278730.642, 120878.463 4...",06,067,005804,06067005804,La_riviera
2,"POLYGON ((118484.777 4273176.598, 118689.226 4...",06,067,005203,06067005203,La_riviera
3,"POLYGON ((119197.121 4275581.295, 119292.682 4...",06,067,009109,06067009109,La_riviera
4,"POLYGON ((121173.805 4278832.06, 121344.525 42...",06,067,005803,06067005803,La_riviera
5,"POLYGON ((123808.733 4278389.86, 123808.112 42...",06,067,009006,06067009006,La_riviera
6,"POLYGON ((114837.276 4277486.301, 114832.988 4...",06,067,005201,06067005201,La_riviera
7,"POLYGON ((117346.391 4278671.9, 117312.967 427...",06,067,005404,06067005404,La_riviera
8,"POLYGON ((120990.696 4278702.974, 120181.252 4...",06,067,009107,06067009107,La_riviera
9,"POLYGON ((118771.957 4276961.927, 118693.692 4...",06,067,009110,06067009110,La_riviera
10,"POLYGON ((123012.816 4281274.724, 122779.299 4...",06,067,008909,06067008909,La_riviera
11,"POLYGON ((119406.006 4277989.833, 118521.327 4...",06,067,009106,06067009106,La_riviera
12,"POLYGON ((118947.261 4276976.94, 118963.147 42...",06,067,009105,06067009105,La_riviera

## Getting data from the Decennial census

The `Sf3` class supports user user queries to the decennial summary file 3 census product for `1990` and `2000`. The `Sf3` is not available for 2010 and it is recommended that the user looks at the American community survey 5 year product for 2010.

Parameters for the `Sf3` include:
   * `features`: dictionary of features from the tigerweb data pull
   * `year`: year of census data request (1990 and 2000 are supported)
   * `apikey`: user's specific census api key string

In [12]:
sf3 = Sf3(tigweb.features, 2000, apikey)

__pulling data using the `get_data()` method__:

The `get_data()` method is defined with a number of default parameters to work with the `TigerWeb` class. Of note, it can automatically determine the finest resolution of data it can pull from the product information and the features supplied to it. The user can also specify this. Parameters for the `get_data()` method include:
   * `level`: default is finest, or the user can set it to their TigerWeb resolution
   * `variables`: default pulls population and economic variables for the census designated place. The user can alternatively supply a tuple of census variables.
   * `retry`: default 100. Retry facilitates a number of data request retries for intermittent internet outages and/or slow connections.

In [13]:
sf3.get_data(level='tract')

Getting tract data for GEOID 06067005202
Getting tract data for GEOID 06067005804
Getting tract data for GEOID 06067005203
Getting tract data for GEOID 06067009109
Getting tract data for GEOID 06067005803
Getting tract data for GEOID 06067009006
Getting tract data for GEOID 06067005201
Getting tract data for GEOID 06067005404
Getting tract data for GEOID 06067009107
Getting tract data for GEOID 06067009110
Getting tract data for GEOID 06067008909
Getting tract data for GEOID 06067009106
Getting tract data for GEOID 06067009105
Getting tract data for GEOID 06067002900
Error getting tract data for GEOID 06067002900
Getting tract data for GEOID 06067004401
Getting tract data for GEOID 06067003000
Error getting tract data for GEOID 06067003000
Getting tract data for GEOID 06067001700
Error getting tract data for GEOID 06067001700
Getting tract data for GEOID 06067002800
Error getting tract data for GEOID 06067002800
Getting tract data for GEOID 06067001800
Error getting tract data for GEOID 06067001800

Data is stored as a geopandas dataframe in the Sf3 class.

In [15]:
features = sf3.features
features.head()

,geometry,STATE,COUNTY,TRACT,GEOID,name,P001001,P052001,P052002,P052003,...,P052010,P052011,P052012,P052013,P052014,P052015,P052016,P052017,HCT012001,H035001
0,"POLYGON ((116650.003 4277424.314, 116443.385 4...",06,067,005202,06067005202,La_riviera,3206.0,1463.0,153.0,52.0,...,89.0,125.0,205.0,133.0,70.0,27.0,32.0,8.0,44074.0,1973.0
1,"POLYGON ((120975.148 4278730.642, 120878.463 4...",06,067,005804,06067005804,La_riviera,2659.0,1115.0,84.0,49.0,...,51.0,68.0,73.0,170.0,98.0,78.0,112.0,156.0,80295.0,1972.0
2,"POLYGON ((118484.777 4273176.598, 118689.226 4...",06,067,005203,06067005203,La_riviera,7140.0,3220.0,295.0,164.0,...,152.0,265.0,409.0,279.0,202.0,106.0,65.0,10.0,41712.0,1969.0
3,"POLYGON ((119197.121 4275581.295, 119292.682 4...",06,067,009109,06067009109,La_riviera,5096.0,1761.0,44.0,19.0,...,117.0,211.0,278.0,308.0,167.0,60.0,67.0,4.0,60264.0,1974.0
4,"POLYGON ((121173.805 4278832.06, 121344.525 42...",06,067,005803,06067005803,La_riviera,3491.0,1428.0,60.0,15.0,...,70.0,114.0,129.0,174.0,158.0,139.0,114.0,182.0,81325.0,1966.0

The user can also define their own variables to grab by supplying census variable names or by using the `Sf3Variables` or `Sf3Variables1990` objects.

Let's redo the data pull and only grab population and median income

In [17]:
from censusdc import Sf3Variables

variables = (Sf3Variables.population, Sf3Variables.median_income)
sf3.get_data(level='finest', variables=variables)

sf3.features.head()

Getting tract data for GEOID 06067005202
Getting tract data for GEOID 06067005804
Getting tract data for GEOID 06067005203
Getting tract data for GEOID 06067009109
Getting tract data for GEOID 06067005803
Getting tract data for GEOID 06067009006
Getting tract data for GEOID 06067005201
Getting tract data for GEOID 06067005404
Getting tract data for GEOID 06067009107
Getting tract data for GEOID 06067009110
Getting tract data for GEOID 06067008909
Getting tract data for GEOID 06067009106
Getting tract data for GEOID 06067009105
Getting tract data for GEOID 06067002900
Error getting tract data for GEOID 06067002900
Getting tract data for GEOID 06067004401
Getting tract data for GEOID 06067003000
Error getting tract data for GEOID 06067003000
Getting tract data for GEOID 06067001700
Error getting tract data for GEOID 06067001700
Getting tract data for GEOID 06067002800
Error getting tract data for GEOID 06067002800
Getting tract data for GEOID 06067001800
Error getting tract data for GEOID 06067001800

,geometry,STATE,COUNTY,TRACT,GEOID,name,P001001,HCT012001
0,"POLYGON ((116650.003 4277424.314, 116443.385 4...",06,067,005202,06067005202,La_riviera,3206.0,44074.0
1,"POLYGON ((120975.148 4278730.642, 120878.463 4...",06,067,005804,06067005804,La_riviera,2659.0,80295.0
2,"POLYGON ((118484.777 4273176.598, 118689.226 4...",06,067,005203,06067005203,La_riviera,7140.0,41712.0
3,"POLYGON ((119197.121 4275581.295, 119292.682 4...",06,067,009109,06067009109,La_riviera,5096.0,60264.0
4,"POLYGON ((121173.805 4278832.06, 121344.525 42...",06,067,005803,06067005803,La_riviera,3491.0,81325.0

## Grabbing data from the American Community Survey Products

The syntax for grabbing data from the American Community Survey Products is the same as grabbing data from the Summary File 3 which was shown in the prior example. Some notes and gotchas are as follows:

__Note__:
   * ACS1 data is available for 2005 through 2018
   * ACS5 data is available for 2009 through 2018

__Gotcha's__:
   * Although the finest resolution for ACS1 is `level=county_subdivision`, it is highly reccomended to specify `level=county` for ACS1 data. The census api has been unreliable for returning county_subdivision data from the ACS1 products.

In [19]:
# An ACS1 example
from censusdc import AcsVariables
year = 2005
level = "county"

tigweb = TigerWeb(gdf, field='name')
tigweb.get_data(year, level=level)


variables = (AcsVariables.population, AcsVariables.median_income)
acs1 = Acs1(tigweb.features, year, apikey)
acs1.get_data(level=level, variables=variables)

feats = acs1.features
feats.head()

Received 1 entries, 1 total, from server 1
Received 1 entries, 1 total, from server 1
Getting county data for GEOID 06067
Getting county data for GEOID 06067

,geometry,GEOID,STATE,COUNTY,AREALAND,AREAWATER,name,B01003_001E,B19013_001E
0,"POLYGON ((111452.756 4243499.119, 111472.855 4...",06067,06,067,2500322890,75063499,La_riviera,1337942.0,51793.0
1,"POLYGON ((111452.756 4243499.119, 111472.855 4...",06067,06,067,2500322890,75063499,La_riviera,1337942.0,51793.0
2,"POLYGON ((111452.756 4243499.119, 111472.855 4...",06067,06,067,2500322890,75063499,Tahoe_park,1337942.0,51793.0
3,"POLYGON ((111452.756 4243499.119, 111472.855 4...",06067,06,067,2500322890,75063499,Tahoe_park,1337942.0,51793.0

In [20]:
# An ACS5 example
year = 2010
level = "tract"

tigweb = TigerWeb(gdf, field="name")
tigweb.get_data(year, level=level)

variables = (AcsVariables.population, AcsVariables.median_income)
acs5 = Acs5(tigweb.features, year, apikey)
acs5.get_data(level=level, variables=variables)

features = acs5.features
features

Received 14 entries, 14 total, from server 10
Received 6 entries, 6 total, from server 10
Getting tract data for GEOID 06067005204
Getting tract data for GEOID 06067005205
Getting tract data for GEOID 06067009006
Getting tract data for GEOID 06067009109
Getting tract data for GEOID 06067009107
Getting tract data for GEOID 06067009106
Getting tract data for GEOID 06067005803
Getting tract data for GEOID 06067005804
Getting tract data for GEOID 06067009110
Getting tract data for GEOID 06067008909
Getting tract data for GEOID 06067005201
Getting tract data for GEOID 06067005202
Getting tract data for GEOID 06067009105
Getting tract data for GEOID 06067005404
Getting tract data for GEOID 06067001800
Getting tract data for GEOID 06067004401
Getting tract data for GEOID 06067002800
Getting tract data for GEOID 06067002900
Getting tract data for GEOID 06067003000
Getting tract data for GEOID 06067001700

,geometry,STATE,COUNTY,TRACT,GEOID,name
0,"POLYGON ((116650.003 4277424.314, 116443.385 4...",06,067,005202,06067005202,La_riviera
1,"POLYGON ((120975.148 4278730.642, 120878.463 4...",06,067,005804,06067005804,La_riviera
2,"POLYGON ((118484.777 4273176.598, 118689.226 4...",06,067,005203,06067005203,La_riviera
3,"POLYGON ((119197.121 4275581.295, 119292.682 4...",06,067,009109,06067009109,La_riviera
4,"POLYGON ((121173.805 4278832.06, 121344.525 42...",06,067,005803,06067005803,La_riviera
5,"POLYGON ((123808.733 4278389.86, 123808.112 42...",06,067,009006,06067009006,La_riviera
6,"POLYGON ((114837.276 4277486.301, 114832.988 4...",06,067,005201,06067005201,La_riviera
7,"POLYGON ((117346.391 4278671.9, 117312.967 427...",06,067,005404,06067005404,La_riviera
8,"POLYGON ((120990.696 4278702.974, 120181.252 4...",06,067,009107,06067009107,La_riviera
9,"POLYGON ((118771.957 4276961.927, 118693.692 4...",06,067,009110,06067009110,La_riviera
10,"POLYGON ((123012.816 4281274.724, 122779.299 4...",06,067,008909,06067008909,La_riviera
11,"POLYGON ((119406.006 4277989.833, 118521.327 4...",06,067,009106,06067009106,La_riviera
12,"POLYGON ((118947.261 4276976.94, 118963.147 42...",06,067,009105,06067009105,La_riviera

## Performing area weighted intersections on census features:

The `GeoFeatures` class can be used to perform area weighted intersections on the census features and census data.

Let's do a complete example of pulling census data and then intersecting it with one of our defining features from our input shape file.

In [21]:
from censusdc.utils import GeoFeatures

year = 2010
level = "tract"

tigweb = TigerWeb(shp_file, field='name')
tigweb.get_data(year, level=level)


variables = (AcsVariables.population, AcsVariables.median_income)
acs5 = Acs5(tigweb.features, year, apikey)
acs5.get_data(level=level, variables=variables)

AttributeError: 'WindowsPath' object has no attribute 'crs'

### The `GeoFeatures` class parameters:

   * `features`: list of features from census data
   * `name`: optional name tag field

In [16]:
names = acs5.feature_names
feature = acs5.get_feature(names[0])

gf = GeoFeatures(feature)

The `intersect()` method of the GeoFeatures class performs intersections on the input data using a list of polygons, list of shapely polygons, or a list of polygons defined by points. 

__Important__: Polygons must be input into the `intersect()` method in the WGS84 (decimal lat, lon) projection

In [17]:
shp = shapefile.Reader(shp_file)
polygons = [shp.shape(0), ]

gf.intersect(polygons)
gf.intersected_features

[{"geometry": {"coordinates": [[[-121.375053, 38.552937], [-121.386081, 38.548625], [-121.398415, 38.546547], [-121.398728, 38.546637], [-121.398817, 38.546672], [-121.398885, 38.546719], [-121.3989, 38.546734], [-121.398944, 38.546785], [-121.398978, 38.546856], [-121.39899, 38.546931], [-121.398988, 38.54707], [-121.39898, 38.54806], [-121.39897, 38.548176], [-121.398952, 38.548267], [-121.398902, 38.548408], [-121.398836, 38.548527], [-121.398764, 38.548626], [-121.398727, 38.548669], [-121.398609, 38.548782], [-121.39847, 38.548882], [-121.398334, 38.548955], [-121.39821, 38.549008], [-121.398584, 38.549631], [-121.398668, 38.549765], [-121.398776, 38.54991], [-121.398905, 38.550058], [-121.398956, 38.550112], [-121.399063, 38.550247], [-121.399125, 38.550341], [-121.399249, 38.550577], [-121.399414, 38.550863], [-121.399646, 38.550791], [-121.399847, 38.550749], [-121.400017, 38.550726], [-121.40019, 38.550715], [-121.403344, 38.550712], [-121.403351, 38.551414], [-121.403356, 38.552089], [-121.40336, 38.552769], [-121.403365, 38.553428], [-121.403362, 38.553473], [-121.403342, 38.553536], [-121.403315, 38.55358], [-121.40292, 38.554042], [-121.402556, 38.554465], [-121.402524, 38.554496], [-121.402475, 38.554529], [-121.402412, 38.554556], [-121.40142, 38.554819], [-121.401325, 38.554839], [-121.401206, 38.554847], [-121.401088, 38.55484], [-121.400951, 38.55481], [-121.400869, 38.554779], [-121.400794, 38.55486], [-121.400739, 38.554909], [-121.40066, 38.554959], [-121.400583, 38.55499], [-121.397997, 38.555587], [-121.397906, 38.555597], [-121.397794, 38.555591], [-121.397688, 38.555567], [-121.397559, 38.555516], [-121.397488, 38.555596], [-121.397412, 38.55566], [-121.397314, 38.555721], [-121.397217, 38.555764], [-121.397114, 38.555797], [-121.396846, 38.555849], [-121.396468, 38.555903], [-121.395785, 38.555348], [-121.395675, 38.555402], [-121.395559, 38.555443], [-121.395058, 38.555554], [-121.394864, 38.555582], [-121.39468, 38.555594], [-121.394495, 38.555594], [-121.394217, 38.555579], [-121.394045, 38.555585], [-121.393907, 38.555603], [-121.393634, 38.555656], [-121.393612, 38.555793], [-121.393596, 38.555988], [-121.393598, 38.556182], [-121.393617, 38.556377], [-121.393654, 38.556569], [-121.393708, 38.55676], [-121.393806, 38.557019], [-121.393898, 38.557248], [-121.393188, 38.557341], [-121.392836, 38.557388], [-121.392249, 38.557465], [-121.391949, 38.557497], [-121.391742, 38.55752], [-121.39086, 38.557614], [-121.390384, 38.557666], [-121.389467, 38.557764], [-121.38863, 38.557854], [-121.387811, 38.557943], [-121.387333, 38.557994], [-121.386711, 38.558061], [-121.385945, 38.558143], [-121.385344, 38.558209], [-121.385048, 38.558241], [-121.384262, 38.558327], [-121.383531, 38.558407], [-121.382508, 38.558519], [-121.379471, 38.558852], [-121.379321, 38.558633], [-121.379203, 38.558464], [-121.378395, 38.557308], [-121.376606, 38.554969], [-121.376243, 38.554494], [-121.376087, 38.55429], [-121.375441, 38.553445], [-121.375307, 38.553284], [-121.375124, 38.553093], [-121.374997, 38.552965], [-121.375053, 38.552937]]], "type": "Polygon"}, "properties": {"AREAWATER": 0, "B01003_001E": 2350.831662789758, "B19013_001E": 54226.0, "COUNTY": "067", "GEOID": "06067005204", "STATE": "06", "TRACT": "005204", "pop_density": 11172516.318395616}, "type": "Feature"},
 {"geometry": {"coordinates": [[[-121.398441, 38.546543], [-121.409469, 38.547584], [-121.409469, 38.553783], [-121.409349, 38.55381], [-121.408594, 38.554], [-121.404808, 38.554852], [-121.402025, 38.555479], [-121.401772, 38.555536], [-121.401547, 38.555586], [-121.401329, 38.555636], [-121.401071, 38.555693], [-121.400637, 38.555791], [-121.400286, 38.55587], [-121.400016, 38.555931], [-121.398131, 38.556355], [-121.39764, 38.556465], [-121.396545, 38.556711], [-121.395933, 38.556849], [-121.395609, 38.556922], [-121.395449, 38.556952], [-121.394759, 38.557084], [-121.393898, 38.557248], [-121.393806, 38.557019], [-121.393708, 38.55676], [-121.393654, 38.556569], [-121.393617, 38.556377], [-121.393598, 38.556182], [-121.393596, 38.555988], [-121.393612, 38.555793], [-121.393634, 38.555656], [-121.393907, 38.555603], [-121.394045, 38.555585], [-121.394217, 38.555579], [-121.394495, 38.555594], [-121.39468, 38.555594], [-121.394864, 38.555582], [-121.395058, 38.555554], [-121.395559, 38.555443], [-121.395675, 38.555402], [-121.395785, 38.555348], [-121.396468, 38.555903], [-121.396846, 38.555849], [-121.397114, 38.555797], [-121.397217, 38.555764], [-121.397314, 38.555721], [-121.397412, 38.55566], [-121.397488, 38.555596], [-121.397559, 38.555516], [-121.397688, 38.555567], [-121.397794, 38.555591], [-121.397906, 38.555597], [-121.397997, 38.555587], [-121.400583, 38.55499], [-121.40066, 38.554959], [-121.400739, 38.554909], [-121.400794, 38.55486], [-121.400869, 38.554779], [-121.400951, 38.55481], [-121.401088, 38.55484], [-121.401206, 38.554847], [-121.401325, 38.554839], [-121.40142, 38.554819], [-121.402412, 38.554556], [-121.402475, 38.554529], [-121.402524, 38.554496], [-121.402556, 38.554465], [-121.40292, 38.554042], [-121.403315, 38.55358], [-121.403342, 38.553536], [-121.403362, 38.553473], [-121.403365, 38.553428], [-121.40336, 38.552769], [-121.403356, 38.552089], [-121.403351, 38.551414], [-121.403344, 38.550712], [-121.40019, 38.550715], [-121.400017, 38.550726], [-121.399847, 38.550749], [-121.399646, 38.550791], [-121.399414, 38.550863], [-121.399249, 38.550577], [-121.399125, 38.550341], [-121.399063, 38.550247], [-121.398956, 38.550112], [-121.398905, 38.550058], [-121.398776, 38.54991], [-121.398668, 38.549765], [-121.398584, 38.549631], [-121.39821, 38.549008], [-121.398334, 38.548955], [-121.39847, 38.548882], [-121.398609, 38.548782], [-121.398727, 38.548669], [-121.398764, 38.548626], [-121.398836, 38.548527], [-121.398902, 38.548408], [-121.398952, 38.548267], [-121.39897, 38.548176], [-121.39898, 38.54806], [-121.398988, 38.54707], [-121.39899, 38.546931], [-121.398978, 38.546856], [-121.398944, 38.546785], [-121.3989, 38.546734], [-121.398885, 38.546719], [-121.398817, 38.546672], [-121.398728, 38.546637], [-121.398415, 38.546547], [-121.398441, 38.546543]]], "type": "Polygon"}, "properties": {"AREAWATER": 0, "B01003_001E": 172.34234144092278, "B19013_001E": 32612.0, "COUNTY": "067", "GEOID": "06067005205", "STATE": "06", "TRACT": "005205", "pop_density": 2399456.667598488}, "type": "Feature"},
 {"geometry": {"coordinates": [[[-121.326566, 38.57732], [-121.336461, 38.572344], [-121.336461, 38.572381], [-121.336474, 38.572471], [-121.329502, 38.575941], [-121.32736, 38.577006], [-121.326615, 38.577375], [-121.326566, 38.57732]]], "type": "Polygon"}, "properties": {"AREAWATER": 0, "B01003_001E": 16.888244775170193, "B19013_001E": 37333.0, "COUNTY": "067", "GEOID": "06067009006", "STATE": "06", "TRACT": "009006", "pop_density": 15876500.733922018}, "type": "Feature"},
 {"geometry": {"coordinates": [[[-121.374997, 38.552965], [-121.375124, 38.553093], [-121.372419, 38.55445], [-121.371535, 38.554894], [-121.367958, 38.55669], [-121.365487, 38.557931], [-121.362959, 38.5592], [-121.360015, 38.560678], [-121.359441, 38.560967], [-121.358991, 38.561015], [-121.374997, 38.552965]]], "type": "Polygon"}, "properties": {"AREAWATER": 0, "B01003_001E": 77.78965536881584, "B19013_001E": 76328.0, "COUNTY": "067", "GEOID": "06067009109", "STATE": "06", "TRACT": "009109", "pop_density": 26632910.49460688}, "type": "Feature"},
 {"geometry": {"coordinates": [[[-121.358991, 38.561015], [-121.359441, 38.560967], [-121.358428, 38.561475], [-121.358301, 38.561534], [-121.359512, 38.562574], [-121.359943, 38.562942], [-121.36012, 38.563083], [-121.360299, 38.563213], [-121.360526, 38.563363], [-121.360765, 38.563504], [-121.36101, 38.563635], [-121.361266, 38.563756], [-121.361529, 38.563866], [-121.361812, 38.563969], [-121.362167, 38.564079], [-121.36245, 38.564152], [-121.363342, 38.564342], [-121.36363, 38.564396], [-121.363941, 38.564442], [-121.364255, 38.564475], [-121.364631, 38.564497], [-121.364865, 38.564502], [-121.365184, 38.564497], [-121.365394, 38.564486], [-121.36571, 38.564459], [-121.366022, 38.56442], [-121.367437, 38.564185], [-121.371038, 38.563586], [-121.372358, 38.563366], [-121.372563, 38.563337], [-121.37282, 38.563313], [-121.373077, 38.563303], [-121.373336, 38.563307], [-121.373639, 38.56333], [-121.373785, 38.563349], [-121.374038, 38.563392], [-121.374162, 38.563418], [-121.374347, 38.563465], [-121.374588, 38.563538], [-121.374672, 38.563568], [-121.374937, 38.563673], [-121.375156, 38.563778], [-121.375316, 38.563865], [-121.375414, 38.563919], [-121.375617, 38.56402], [-121.37583, 38.564109], [-121.375994, 38.564168], [-121.376217, 38.564237], [-121.376332, 38.564266], [-121.376564, 38.564316], [-121.376776, 38.564349], [-121.376978, 38.564372], [-121.377158, 38.564383], [-121.377279, 38.564387], [-121.37758, 38.564382], [-121.377796, 38.564365], [-121.377897, 38.56435], [-121.378114, 38.564321], [-121.378289, 38.564286], [-121.378937, 38.564118], [-121.37919, 38.564069], [-121.379499, 38.564029], [-121.379526, 38.564027], [-121.37975, 38.564012], [-121.380001, 38.564009], [-121.380314, 38.564024], [-121.380625, 38.564061], [-121.380835, 38.564098], [-121.381009, 38.564129], [-121.381317, 38.564166], [-121.381341, 38.564168], [-121.381548, 38.564181], [-121.381819, 38.564185], [-121.382088, 38.564175], [-121.382224, 38.564164], [-121.382639, 38.564114], [-121.382682, 38.564392], [-121.382706, 38.564685], [-121.382724, 38.565189], [-121.382735, 38.565335], [-121.369729, 38.5684], [-121.368584, 38.568777], [-121.36793, 38.56887], [-121.366495, 38.569074], [-121.366426, 38.569083], [-121.364862, 38.569305], [-121.364588, 38.56943], [-121.364313, 38.569554], [-121.358652, 38.571055], [-121.358386, 38.570724], [-121.357582, 38.5707], [-121.357037, 38.570758], [-121.356525, 38.570891], [-121.356045, 38.571], [-121.355325, 38.571192], [-121.354878, 38.571318], [-121.354551, 38.571325], [-121.35441, 38.571264], [-121.353765, 38.570594], [-121.35342, 38.570055], [-121.353122, 38.569401], [-121.352705, 38.568488], [-121.352372, 38.56786], [-121.35229, 38.567704], [-121.352124, 38.56739], [-121.351913, 38.566993], [-121.351466, 38.565988], [-121.351358, 38.565809], [-121.351242, 38.565617], [-121.351182, 38.565485], [-121.351047, 38.565377], [-121.350928, 38.565311], [-121.350705, 38.565329], [-121.350651, 38.565208], [-121.358991, 38.561015]]], "type": "Polygon"}, "properties": {"AREAWATER": 172671, "B01003_001E": 3391.544361737369, "B19013_001E": 54213.0, "COUNTY": "067", "GEOID": "06067009106", "STATE": "06", "TRACT": "009106", "pop_density": 22008038.20262337}, "type": "Feature"},
 {"geometry": {"coordinates": [[[-121.350651, 38.565208], [-121.350705, 38.565329], [-121.350928, 38.565311], [-121.351047, 38.565377], [-121.351182, 38.565485], [-121.351242, 38.565617], [-121.351358, 38.565809], [-121.351466, 38.565988], [-121.351913, 38.566993], [-121.352124, 38.56739], [-121.35229, 38.567704], [-121.352372, 38.56786], [-121.352705, 38.568488], [-121.353122, 38.569401], [-121.35342, 38.570055], [-121.353765, 38.570594], [-121.35441, 38.571264], [-121.354551, 38.571325], [-121.354878, 38.571318], [-121.355325, 38.571192], [-121.356045, 38.571], [-121.356525, 38.570891], [-121.357037, 38.570758], [-121.357582, 38.5707], [-121.358386, 38.570724], [-121.358652, 38.571055], [-121.351901, 38.574269], [-121.340827, 38.577914], [-121.336369, 38.57839], [-121.336306, 38.578093], [-121.335736, 38.578074], [-121.335596, 38.578062], [-121.335387, 38.578029], [-121.335319, 38.578015], [-121.334179, 38.577737], [-121.333985, 38.577704], [-121.333166, 38.577601], [-121.333262, 38.576899], [-121.333289, 38.576743], [-121.333335, 38.576596], [-121.333397, 38.576454], [-121.33345, 38.576362], [-121.333541, 38.576235], [-121.333652, 38.576112], [-121.333777, 38.575998], [-121.33392, 38.575896], [-121.33402, 38.575834], [-121.334727, 38.575474], [-121.335583, 38.575035], [-121.335743, 38.574936], [-121.335866, 38.57485], [-121.335963, 38.574768], [-121.336035, 38.57469], [-121.336108, 38.574598], [-121.336168, 38.574497], [-121.336217, 38.574392], [-121.336254, 38.57426], [-121.336269, 38.574154], [-121.336271, 38.573943], [-121.336281, 38.573861], [-121.336322, 38.573721], [-121.33643, 38.57349], [-121.336464, 38.573386], [-121.336488, 38.573227], [-121.336488, 38.573174], [-121.336487, 38.572917], [-121.336486, 38.572546], [-121.336474, 38.572471], [-121.336461, 38.572381], [-121.336461, 38.572344], [-121.350651, 38.565208]]], "type": "Polygon"}, "properties": {"AREAWATER": 167427, "B01003_001E": 1973.8719581628754, "B19013_001E": 65861.0, "COUNTY": "067", "GEOID": "06067009107", "STATE": "06", "TRACT": "009107", "pop_density": 13220308.649458652}, "type": "Feature"},
 {"geometry": {"coordinates": [[[-121.351901, 38.574269], [-121.358652, 38.571055], [-121.364313, 38.569554], [-121.364588, 38.56943], [-121.364862, 38.569305], [-121.364966, 38.56946], [-121.365062, 38.569605], [-121.365277, 38.569866], [-121.351901, 38.574269]]], "type": "Polygon"}, "properties": {"AREAWATER": 351882, "B01003_001E": 70.02147673860694, "B19013_001E": 105189.0, "COUNTY": "067", "GEOID": "06067005803", "STATE": "06", "TRACT": "005803", "pop_density": 8298607.9747282}, "type": "Feature"},
 {"geometry": {"coordinates": [[[-121.329852, 38.579084], [-121.33007, 38.578955], [-121.330398, 38.578816], [-121.330968, 38.578644], [-121.331554, 38.578575], [-121.332228, 38.578575], [-121.333073, 38.578627], [-121.333555, 38.57869], [-121.329852, 38.579084]]], "type": "Polygon"}, "properties": {"AREAWATER": 325415, "B01003_001E": 6.652570536247369, "B19013_001E": 91667.0, "COUNTY": "067", "GEOID": "06067005804", "STATE": "06", "TRACT": "005804", "pop_density": 8465338.24462875}, "type": "Feature"},
 {"geometry": {"coordinates": [[[-121.376316, 38.559184], [-121.375518, 38.559268], [-121.374626, 38.559362], [-121.372628, 38.559572], [-121.372447, 38.559592], [-121.371154, 38.559729], [-121.367339, 38.560132], [-121.359441, 38.560967], [-121.360015, 38.560678], [-121.362959, 38.5592], [-121.365487, 38.557931], [-121.367958, 38.55669], [-121.371535, 38.554894], [-121.372419, 38.55445], [-121.375124, 38.553093], [-121.375307, 38.553284], [-121.375441, 38.553445], [-121.376087, 38.55429], [-121.376243, 38.554494], [-121.376606, 38.554969], [-121.378395, 38.557308], [-121.379203, 38.558464], [-121.379321, 38.558633], [-121.379471, 38.558852], [-121.376316, 38.559184]]], "type": "Polygon"}, "properties": {"AREAWATER": 0, "B01003_001E": 1353.0000000000002, "B19013_001E": 32639.0, "COUNTY": "067", "GEOID": "06067009110", "STATE": "06", "TRACT": "009110", "pop_density": 21606905.912073445}, "type": "Feature"},
 {"geometry": {"coordinates": [[[-121.326615, 38.577375], [-121.32736, 38.577006], [-121.329502, 38.575941], [-121.336474, 38.572471], [-121.336486, 38.572546], [-121.336487, 38.572917], [-121.336488, 38.573174], [-121.336488, 38.573227], [-121.336464, 38.573386], [-121.33643, 38.57349], [-121.336322, 38.573721], [-121.336281, 38.573861], [-121.336271, 38.573943], [-121.336269, 38.574154], [-121.336254, 38.57426], [-121.336217, 38.574392], [-121.336168, 38.574497], [-121.336108, 38.574598], [-121.336035, 38.57469], [-121.335963, 38.574768], [-121.335866, 38.57485], [-121.335743, 38.574936], [-121.335583, 38.575035], [-121.334727, 38.575474], [-121.33402, 38.575834], [-121.33392, 38.575896], [-121.333777, 38.575998], [-121.333652, 38.576112], [-121.333541, 38.576235], [-121.33345, 38.576362], [-121.333397, 38.576454], [-121.333335, 38.576596], [-121.333289, 38.576743], [-121.333262, 38.576899], [-121.333166, 38.577601], [-121.333985, 38.577704], [-121.334179, 38.577737], [-121.335319, 38.578015], [-121.335387, 38.578029], [-121.335596, 38.578062], [-121.335736, 38.578074], [-121.336306, 38.578093], [-121.336369, 38.57839], [-121.333555, 38.57869], [-121.333073, 38.578627], [-121.332228, 38.578575], [-121.331554, 38.578575], [-121.330968, 38.578644], [-121.330398, 38.578816], [-121.33007, 38.578955], [-121.329852, 38.579084], [-121.328277, 38.579252], [-121.326615, 38.577375]]], "type": "Polygon"}, "properties": {"AREAWATER": 205020, "B01003_001E": 218.75006527866688, "B19013_001E": 81667.0, "COUNTY": "067", "GEOID": "06067008909", "STATE": "06", "TRACT": "008909", "pop_density": 7668546.444121973}, "type": "Feature"},
 {"geometry": {"coordinates": [[[-121.409469, 38.559034], [-121.409298, 38.559074], [-121.409299, 38.55905], [-121.409321, 38.558716], [-121.40935, 38.558383], [-121.409386, 38.558051], [-121.409435, 38.557678], [-121.409454, 38.557486], [-121.409465, 38.557254], [-121.409459, 38.557021], [-121.409424, 38.556591], [-121.409407, 38.556386], [-121.409358, 38.555797], [-121.409359, 38.55572], [-121.40937, 38.555564], [-121.409393, 38.555413], [-121.409393, 38.555187], [-121.409352, 38.553903], [-121.409349, 38.55381], [-121.409469, 38.553783], [-121.409469, 38.559034]]], "type": "Polygon"}, "properties": {"AREAWATER": 178418, "B01003_001E": 5.170228412586517, "B19013_001E": 25472.0, "COUNTY": "067", "GEOID": "06067005201", "STATE": "06", "TRACT": "005201", "pop_density": 12110732.270649135}, "type": "Feature"},
 {"geometry": {"coordinates": [[[-121.382735, 38.565335], [-121.382724, 38.565189], [-121.382706, 38.564685], [-121.382682, 38.564392], [-121.382639, 38.564114], [-121.382613, 38.563974], [-121.382577, 38.563825], [-121.382531, 38.563658], [-121.382492, 38.563556], [-121.382383, 38.563275], [-121.382305, 38.563089], [-121.382175, 38.562815], [-121.382027, 38.562546], [-121.38186, 38.562284], [-121.381644, 38.561978], [-121.380787, 38.560773], [-121.379566, 38.558988], [-121.379471, 38.558852], [-121.382508, 38.558519], [-121.383531, 38.558407], [-121.384262, 38.558327], [-121.385048, 38.558241], [-121.385344, 38.558209], [-121.385945, 38.558143], [-121.386711, 38.558061], [-121.387333, 38.557994], [-121.387811, 38.557943], [-121.38863, 38.557854], [-121.389467, 38.557764], [-121.390384, 38.557666], [-121.39086, 38.557614], [-121.391742, 38.55752], [-121.391949, 38.557497], [-121.392249, 38.557465], [-121.392836, 38.557388], [-121.393188, 38.557341], [-121.393898, 38.557248], [-121.394759, 38.557084], [-121.395449, 38.556952], [-121.395609, 38.556922], [-121.395933, 38.556849], [-121.396545, 38.556711], [-121.39764, 38.556465], [-121.398131, 38.556355], [-121.400016, 38.555931], [-121.400286, 38.55587], [-121.400637, 38.555791], [-121.401071, 38.555693], [-121.401329, 38.555636], [-121.401547, 38.555586], [-121.401772, 38.555536], [-121.402025, 38.555479], [-121.404808, 38.554852], [-121.408594, 38.554], [-121.409349, 38.55381], [-121.409352, 38.553903], [-121.409393, 38.555187], [-121.409393, 38.555413], [-121.40937, 38.555564], [-121.409359, 38.55572], [-121.409358, 38.555797], [-121.409407, 38.556386], [-121.409424, 38.556591], [-121.409459, 38.557021], [-121.409465, 38.557254], [-121.409454, 38.557486], [-121.409435, 38.557678], [-121.409386, 38.558051], [-121.40935, 38.558383], [-121.409321, 38.558716], [-121.409299, 38.55905], [-121.409298, 38.559074], [-121.382735, 38.565335]]], "type": "Polygon"}, "properties": {"AREAWATER": 370980, "B01003_001E": 2769.5287793003554, "B19013_001E": 61598.0, "COUNTY": "067", "GEOID": "06067005202", "STATE": "06", "TRACT": "005202", "pop_density": 17379155.433746513}, "type": "Feature"},

This output can also be accumulated into a pandas dataframe with human readable output by using the `GeoFeatures.features_to_dataframe` method.

In [18]:
df = GeoFeatures.features_to_dataframe(year, gf.intersected_features)
df

   year   B01003_001E   B19013_001E   pop_density
0  2010  15891.969098  59605.642857  1.554997e+07

Optionally we can use the `hr_dict` flag and supply a dictionary of human readable tags to the `GeoFeatures.features_to_dataframe` method. 

For variables in `AcsVariables`, `Sf3Variables`, and `Sf3Variables1990` there are associated built in human readable associations in the:

* `AcsHR`
* `Sf3HR`
* `Sf3HR1990`

In [19]:
from censusdc.datacollector import Sf3HR, Sf3HR1990, AcsHR 

df = GeoFeatures.features_to_dataframe(year, gf.intersected_features, Sf3HR1990)
df

   year   B01003_001E   B19013_001E   pop_density
0  2010  15891.969098  59605.642857  1.554997e+07

## The next notebook: Notebook 2, shows how to use the `CensusTimeSeries` class which combines all of these methods on the backend to return a human readable time series of all available census data for the selected variables!